title: Main Page
author:
  name: wojciechjablonsk1
  email: woj.jablo@gmail.com

description: >
  Embedded Systems + Robotics + Mechanical Design Engineer

remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic

  nav_pages:
    - about.md
    - portfolio.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
social_links:
  - title: GitHub
    icon: github
    url: https://github.com/wojciechjablonsk1

  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/YOUR-LINKEDIN
