# Website settings
show_downloads: false

# Theme
theme: minima

# Social links
github_username: wojciechjablonsk1

# Build settings
markdown: kramdown

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
